# Extra autostart processes
# exec-once = waybar
#exec-once = swww-daemon
#exec-once = swww img ~/Pictures/static-wallpaper.png
exec-once = hyprpm reload
exec-once = wal -i ~/Pictures/wallhaven-main.png
exec-once = swaync
